insert into atlas2 (nome_veiculo, apenas_digital, blog_site_pag, segmento_principal, caracteristicas, orientacao_politica, modelo_negocios, proprietario, regiao, uf, cidade, codmun, endereco,
link, twitter, facebook, rss, obs, colaborador, email_veiculo, organizacao, funcionarios, periodicidade)
values("AMETISTA AM",
"Não",
"Não",
"Rádio",
"Opinião/colunistas, Newsletters",
"Não declara posição política/Não é possível identificar",
"Publicidade (outros tipos)",
"GRUPO PONTO NORTE",
"Sul",
"RS",	
"PLANALTO",	
"4314704",	
"Av. Daltro Filho, 1000, Bairro: Centro - Planalto / RS",	
"http://www.pontonortefm.com.br",	"",
"https://www.facebook.com/www.radioametista.com.br/",	
"",	
"",	
"Dono / administrador / representante de veículo de jornalismo (exceto jornalista de redação)",
"radioametista@hotmail.com",	
"",	
"10 a 29 colaboradores",
"Diário")